### ISSUE TITLE
Login: Enter does nothing

### ISSUE THREAD

**Issue by KamTinsley** [elahi-arman/COEN174-SoftwareEngr#4]
Hitting enter after entering COEN/COEN for username/password generates a popup warning saying that you have successfully logged in.  Then it proceeds to do nothing, making you click the submit button if you truly want to be logged in.

**Comment by elahi-arman** [comment]
This should be fixed in the latest commit, was a change for a line in the anonymous ```document.onkeypress function```. Where now we have 

``` javascript

if (valid){
          window.location = 'advisors.html';
 }

```

**Comment by KamTinsley** [comment]
Enter now does nothing at all.  Intended?
